### ISSUE TITLE
Annotation Charts: Some languages are placed in the wrong family page

### ISSUE THREAD

**Issue by iwsfutcmd** [unicode-org/cldr-staging#7]
In the Annotation Charts, the columns for some languages are placed on the wrong language family page.

* "Cebuano" is under "Other" when it should be under "Austronesian"
* "Kurdish" is under "Other" when it should be under "Other Indo-European"

There will also now be 3 Iranian languages under "Other Indo-European", so it might be a good idea to have a new page for "Iranian" with Persian, Pashto, and Kurdish under it.

Note: I'd just make a pull request fixing this, but I figured there was already some kind of build script out there for making these charts so I held back. If you can point me towards where those build scripts are, I can generate the charts and do a pull request.

**Comment by macchiati** [comment]
That'd be great. The source file to change is
https://github.com/unicode-org/cldr/blob/master/tools/java/org/unicode/cldr/util/LanguageGroup.java,
and you'll need to file a ticket first (
http://cldr.unicode.org/index/bug-reports#TOC-Filing-a-Ticket). Once that
is done, the next time the charts are generated they will have the fix.

Mark

**Comment by iwsfutcmd** [comment]
Fixed by https://github.com/unicode-org/cldr/pull/507, closing...
